### ISSUE TITLE
Dockerized variant tools fails to run SKAT association test

### ISSUE THREAD

**Issue by kromanenkov** [vatlab/VariantTools#88]
Variant tools presented in mdabioinfo/varianttools image is based on python3.5. Running SKAT association in this way:
`vtools associate variant -m "SKAT" ...`
leads to
"Failed to load association test SKAT: a bytes-like object is required, not „str”.Please use command «vtools show tests» to list usable tests" error.

When python2.7 based variant tools is installed (with pip) everything works fine.

**Comment by BoPeng** [comment]
Thanks for reporting this. This is a bug that has been resolved but we have not updated the docker image. 

@jma7 Is it ready for us to update our docker image with the latest release?

**Comment by jma7** [comment]
@BoPeng Bo will update the docker image with conda install to install VariantTools later.

**Comment by gaow** [comment]
Any updates on the docker image or `conda` distribution?  I've got an inquiry regarding reproducing:

https://gaow.github.io/ismb-2018

but looks like there are some kinks to iron out there. Would be nice to release a version that works for it.

**Comment by jma7** [comment]
@BoPeng Will you update the conda distribution?

**Comment by oyvindbusk** [comment]
Hi, 

I still get this error when using docker. Did you update the docker image?

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/54160599-f6fc9700-441d-11e9-8e05-a802fea2bd64.png)

I can reproduce this report and I am trying to fix it.

**Comment by BoPeng** [comment]
@gaow 

The following patch fixes the `bytes-like object` error. Please let me if it is safe to do so

```diff
diff --git a/src/variant_tools/rtester.py b/src/variant_tools/rtester.py
index 7802121f..dc714016 100644
--- a/src/variant_tools/rtester.py
+++ b/src/variant_tools/rtester.py
@@ -152,7 +152,7 @@ class RConfig:
         configstr = self.load(rlist)
         if configstr is None:
             return
-        self.conf.readfp(io.BytesIO(configstr))
+        self.conf.readfp(io.StringIO(configstr))
         for section in self.conf.sections():
             try:
                 self.parse(section)
```

**Comment by gaow** [comment]
@BoPeng It looks like a python 2 vs 3 relic ... I think we should apply this patch and worry about it later if we have to revisit Python 2 support.

**Comment by kromanenkov** [comment]
I can confirm that this patch fixes the error. BTW, you need to update Dockerfile to use hdf5 1.10.5.

**Comment by BoPeng** [comment]
I have released variant tools 3.0.2 and updated docker image (with hdf5 1.10.5)
